# Generated by Django 5.0.3 on 2024-03-31 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
    ]
